---
- name: template configuration
  template:
    src: "{{ rad_conf_item.value.filename }}.j2"
    dest: "{{ freeradius_conf_dir }}/{{ rad_conf_item.value.filename }}"
    mode: 0644
  with_dict: "{{ freeradius.config }}"
  # loop: "{{ freeradius.config|dict2items }}"
  loop_control:
    loop_var: rad_conf_item
  when: >
    rad_conf_item.value.disabled is undefined or (
      rad_conf_item.value.disabled is defined and
      not rad_conf_item.value.disabled
    )
  notify: restart-radius
  register: template_config
  tags: config

- name: get contents of config dir
  command: "find {{ freeradius_conf_dir }}/ -maxdepth 1 -type f"
  register: configfiles
  check_mode: no
  changed_when: False
  tags: config

- name: list of items never to delete
  set_fact:
    safelist:
      - "{{ freeradius_conf_dir }}/mods-available"
      - "{{ freeradius_conf_dir }}/mods-config"
      - "{{ freeradius_conf_dir }}/mods-enabled"
      - "{{ freeradius_conf_dir }}/policy.d"
      - "{{ freeradius_conf_dir }}/README.rst"
      - "{{ freeradius_conf_dir }}/sites-available"
      - "{{ freeradius_conf_dir }}/sites-enabled"
      - "{{ freeradius_conf_dir }}/users"
      - "{{ freeradius_conf_dir }}/radiusd.conf"
  tags: config

- name: delete unmanaged config
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ configfiles.stdout_lines }}"
  when:
    - item not in template_config.results|selectattr('dest', 'string')|map(attribute='dest')|list
    - item not in safelist
  notify: restart-radius
  tags: config
...