---
- name: copy site configuration
  copy:
    src: "{{ item.value.config_file }}"
    dest: "{{ freeradius_conf_dir }}/sites-available/{{ item.key }}"
    mode: 0644
  with_dict: "{{ freeradius.sites }}"
  when:
    - item.value.disabled is undefined or (item.value.disabled is defined and not item.value.disabled)
    - item.value.config_file is defined
  notify: restart-radius

- name: enable sites by symlinking them
  file:
    src: "../sites-available/{{ item.key }}"
    path: "{{ freeradius_conf_dir }}/sites-enabled/{{ item.key }}"
    state: link
  with_dict: "{{ freeradius.sites }}"
  when: item.value.disabled is undefined or (item.value.disabled is defined and not item.value.disabled)
  register: enable_mod_result
  notify: restart-radius

- name: get contents of sites-enabled dir
  shell: "ls -1 {{ freeradius_conf_dir }}/sites-enabled/*"
  register: sitesenabled_contents
  check_mode: no
  changed_when: false

- name: delete old sites-enabled
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ sitesenabled_contents.stdout_lines }}"
  when: item not in enable_mod_result.results|selectattr('dest', 'string')|map(attribute='dest')|list
  notify: restart-radius

...