---
# Ubuntu creates a 3.0 directory that is not used with the packages from the repo.
- name: check ubuntu config dir
  stat:
    path: /etc/freeradius/3.0
  register: freeradius_3_configdir
  tags:
    - radius
    - ubuntu-radius-config-dir

- name: copy existing config dir
  copy:
    remote_src: True
    src: /etc/freeradius/3.0/
    dest: /etc/freeradius/3.0_old
    mode: 0644
  when:
    - freeradius_3_configdir.stat.exists
    - freeradius_3_configdir.stat.isdir is defined and freeradius_3_configdir.stat.isdir
  tags:
    - radius
    - ubuntu-radius-config-dir

- name: remove existing config dir
  file:
    path: /etc/freeradius/3.0
    state: absent
  when: freeradius_3_configdir.stat.isdir is defined and freeradius_3_configdir.stat.isdir
  tags:
    - radius
    - ubuntu-radius-config-dir

- name: symlink config dir to old path for backwards compatibility
  file:
    src: /etc/freeradius
    dest: /etc/freeradius/3.0
    state: link
  tags:
    - radius
    - ubuntu-radius-config-dir
  when: not ansible_check_mode
...